const creditCardSpendingCategories = [
	"Adobe Creative Solutions",
	"Advertising",
	"Alcohol and Bars",
	"Amazon",
	"Amazon Fresh",
	"Automotive",
	"Beauty and Wellness",
	"Books and Magazines",
	"Car Rentals",
	"Charity",
	"Chase Dining",
	"Chase Travel",
	"CLEAR Plus Credit",
	"Coffee Shops",
	"Concerts and Events",
	"Cosmetics",
	"Costco",
	"Dell",
	"Delta",
	"Digital Entertainment",
	"Dining",
	"Disney Bundle",
	"Dry Cleaning",
	"Education",
	"Electronics",
	"Eligible Business Purchases",
	"Entertainment",
	"Equinox",
	"Everything Else",
	"Fast Food",
	"Flights",
	"Flights Credit",
	"Furniture",
	"Gas Stations",
	"Gifts and Special Occasions",
	"Groceries",
	"Healthcare",
	"Hilton",
	"Hobbies and Crafts",
	"Home Appliances",
	"Home Improvement",
	"Hotels",
	"Hotel Credit",
	"Household Supplies",
	"Indeed",
	"Insurance",
	"Internet, Cable, and Phone Services",
	"Jewelry",
	"Lyft",
	"Marriott",
	"Mobile Payments",
	"Movies and Theaters",
	"Music and Instruments",
	"Office Supplies",
	"Online Shopping",
	"Outdoor Recreation",
	"Parking",
	"Pet Care",
	"Pharmacies",
	"Photography",
	"Public Transit",
	"Ride-Sharing",
	"Saks Fifth Avenue",
	"Shipping",
	"Southwest Airlines",
	"Sports and Fitness",
	"Streaming Services",
	"Subscriptions",
	"Target",
	"Taxis and Limousines",
	"Technology",
	"Telecommunications",
	"Toys and Games",
	"Transportation",
	"Travel",
	"Uber",
	"Utilities",
	"Video Games",
	"Walmart",
	"Weddings",
	"Whole Foods Market",
	"Workwear and Uniforms"
] as const

export default creditCardSpendingCategories
