const creditCardSpendingCategories = [
	"Ace Hardware",
	"Apple Products and Services",
	"Apple Pay",
	"Adobe Creative Solutions",
	"Advertising",
	"Alcohol and Bars",
	"Amazon",
	"Amazon Fresh",
	"Automotive",
	"Beauty and Wellness",
	"Books and Magazines",
	"Brex Travel",
	"Car Rentals",
	"Charity",
	"Chase Dining",
	"Chase Travel",
	"Citi Travel",
	"CLEAR Plus Credit",
	"Coffee Shops",
	"Concerts and Events",
	"Cosmetics",
	"Costco",
	"Dell",
	"Delta",
	"Digital Entertainment",
	"Dining",
	"Disney Bundle",
	"Dry Cleaning",
	"Duane Reade",
	"Education",
	"Electronics",
	"Eligible Business Purchases",
	"Entertainment",
	"Equinox",
	"Everything Else",
	"Expedia",
	"Exxon",
	"Fast Food",
	"Fitness Club and Gym Memberships",
	"Flights",
	"Flights Credit",
	"Furniture",
	"Gas Stations",
	"Gifts and Special Occasions",
	"Groceries",
	"Healthcare",
	"Hilton",
	"Hobbies and Crafts",
	"Home Appliances",
	"Home Chef",
	"Home Improvement",
	"Hotels",
	"Hotel Credit",
	"Household Supplies",
	"Hyatt",
	"Indeed",
	"Insurance",
	"Internet, Cable, and Phone Services",
	"Jewelry",
	"Large Purchases",
	"Lyft",
	"Marriott",
	"Mobil",
	"Mobile Payments",
	"Movies and Theaters",
	"Music and Instruments",
	"Nike",
	"Office Supplies",
	"Online Shopping",
	"Outdoor Recreation",
	"Panera Bread",
	"Parking",
	"Pet Care",
	"Pharmacies",
	"Photography",
	"Public Transit",
	"Rapid Rewards hotel and car rental partner purchases",
	"Rent",
	"Reoccurring Software",
	"Ride-Sharing",
	"Saks Fifth Avenue",
	"Shipping",
	"Social Media and Search Engine Advertising",
	"Southwest Airlines",
	"Sports and Fitness",
	"Streaming Services",
	"Subscriptions",
	"T-Mobile",
	"Target",
	"Taxis and Limousines",
	"Technology",
	"Telephone Service Providers",
	"Toys and Games",
	"Transportation",
	"Travel",
	"Uber",
	"United Airlines",
	"Utilities",
	"U.S. Online Retail Purhchases",
	"Variable Spending Category",
	"Video Games",
	"Walgreens",
	"Walmart",
	"Weddings",
	"Whole Foods Market",
	"Workwear and Uniforms"
] as const

export default creditCardSpendingCategories
