const creditCardNames = [
	"Aeromexico Visa Business",
	"Amazon Prime Rewards Visa Signature",
	"Amazon Prime Store Card",
	"Amazon Rewards Visa Signature",
	"Amazon Store Card",
	"American Express® Green Card",
	"American Express Preferred Credit Card",
	"American Express® Gold Card",
	"Amex EveryDay® Credit Card",
	"Apple Card",
	"Bank of America Business Advantage Cash Rewards Mastercard",
	"Bank of America Customized Cash Rewards",
	"Bank of America Travel Rewards",
	"Barclaycard Arrival Plus World Elite Mastercard Business Credit Card",
	"Blue Business Plus Credit Card from American Express",
	"Blue Cash Everyday® Card",
	"Blue Cash Preferred® Card",
	"Bilt Mastercard®",
	"Brex Corporate Card for Startups",
	"Capital One Platinum Credit Card",
	"Capital One QuicksilverOne Cash Rewards",
	"Capital One Savor",
	"Capital One SavorOne",
	"Capital One Spark Cash Plus",
	"Capital One Spark Cash Select Business Credit Card",
	"Capital One Spark Miles Business Credit Card",
	"Capital One Spark Miles Select Business Credit Card",
	"Capital One Venture X",
	"CareCredit Rewards Mastercard",
	"Cash Magnet® Card",
	"Cathay Pacific Visa Business Card",
	"Chase Freedom Flex Credit Card",
	"Chase Freedom Rise",
	"Chase Freedom Student Credit Card",
	"Chase Freedom Unlimited® Credit Card",
	"Chase Ink Business Cash Credit Card",
	"Chase Sapphire Preferred® Credit Card",
	"Chase Sapphire Reserve",
	"Citi Custom Cash® Card",
	"Citi Double Cash® Credit Card",
	"Citi Premier",
	"Costco Anywhere Visa",
	"Credit One Bank Platinum Visa",
	"Credit One Bank Unsecured Visa",
	"Delta SkyMiles® Blue American Express Card",
	"Delta SkyMiles® Gold American Express Card",
	"Delta SkyMiles® Platinum American Express Card",
	"Delta SkyMiles® Platinum Business Card",
	"Delta SkyMiles® Reserve American Express Card",
	"Deserve Edu Mastercard for Students",
	"Deserve Pro Mastercard",
	"Discover it Cash Back",
	"Discover it Miles",
	"Discover it Secured Credit Card",
	"Discover it Student Cash Back",
	"Fidelity® Rewards Visa Signature® Credit Card",
	"First Access Visa Credit Card",
	"First Progress Platinum Prestige Mastercard",
	"FortuneCard Mastercard",
	"Gemini Credit Card®",
	"Hilton Honors Card",
	"Hilton Honors American Express Surpass® Card",
	"Hilton Honors American Express Aspire Card",
	"HSBC Premier World Elite Mastercard",
	"IHG Rewards Premier",
	"Indigo Platinum Mastercard",
	"Ink Business Preferred Credit Card",
	"Ink Business Unlimited Credit Card",
	"Marriott Bonvoy Boundless",
	"Merrick Bank Double Your Line Credit Card",
	"Milestone Gold Mastercard",
	"PayPal Cashback Mastercard",
	"PenFed Platinum Rewards Visa Signature",
	"PenFed Power Cash Rewards Visa Signature",
	"Petal 1 Visa Credit Card",
	"Radisson Rewards Premier Visa Signature",
	"SoFi Credit Card",
	"Southwest Priority",
	"Southwest Rapid Rewards Premier Business Credit Card",
	"Surge Chrome Visa Credit Card",
	"Surge Mastercard",
	"TD Double Up Visa Credit Card",
	"TD First Class Visa Signature Credit Card",
	"The Business Platinum Card from American Express",
	"The Platinum Card®",
	"Turkish Airlines Elite Visa Business Card",
	"U.S. Bank Business Leverage Visa Card",
	"United Business Card",
	"United Explorer Card",
	"Wells Fargo Active Cash Card",
	"Wells Fargo Business Platinum Credit Card",
	"Wells Fargo Propel",
	"World of Hyatt Credit Card",
	"Wyndham Rewards Earner Plus",
	"X1 Card"
] as const

export default creditCardNames
