const creditCardSpendingCategories = [
	"Ace Hardware",
	"Apple Products and Services",
	"Apple Pay",
	"Adobe Creative Solutions",
	"Advertising",
	"Amazon",
	"Amazon Fresh",
	"Brex Travel",
	"Car Rentals",
	"Charity",
	"Chase Dining",
	"Chase Travel",
	"Citi Travel",
	"CLEAR Plus",
	"Costco",
	"Dell",
	"Delta",
	"Digital Entertainment",
	"Dining",
	"Disney Bundle",
	"Duane Reade",
	"Eligible Business Purchases",
	"Entertainment",
	"Equinox",
	"Everything Else",
	"Expedia",
	"Exxon",
	"Fitness Club and Gym Memberships",
	"Flights",
	"Flights Credit",
	"Gas Stations",
	"Groceries",
	"Hilton",
	"Home Chef",
	"Hotels",
	"Hotel Credit",
	"Hyatt",
	"IHG® Hotels and Resorts",
	"Indeed",
	"Internet, Cable, and Phone Services",
	"Large Purchases",
	"Lyft",
	"Marriott",
	"Mobil",
	"Nike",
	"Office Supplies",
	"Online Shopping",
	"Panera Bread",
	"Pharmacies",
	"Public Transit",
	"Rapid Rewards hotel and car rental partner purchases",
	"Rent",
	"Reoccurring Software",
	"Ride-Sharing",
	"Saks Fifth Avenue",
	"Shipping",
	"Social Media and Search Engine Advertising",
	"Southwest Airlines",
	"Streaming Services",
	"T-Mobile",
	"Target",
	"Telephone Service Providers",
	"Transportation",
	"Travel",
	"Uber",
	"United Airlines",
	"U.S. Online Retail Purchases",
	"Variable Spending Category",
	"Walgreens",
	"Walmart",
	"Whole Foods Market",
	"Wyndham"
] as const

export default creditCardSpendingCategories
