const creditCardNames = [
	"Amazon Prime Rewards Visa Signature",
	"Amazon Store Card",
	"Amazon Rewards Visa Signature",
	"American Express® Green Card",
	"American Express® Gold Card",
	"Amex EveryDay® Credit Card",
	"Apple Card",
	"Bank of America Customized Cash Rewards",
	"Bank of America® Travel Rewards Credit Card",
	"Blue Business® Plus Credit Card",
	"Blue Cash Everyday® Card",
	"Blue Cash Preferred® Card",
	"Bilt Mastercard®",
	"Brex Corporate Card for Startups",
	"Platinum Mastercard® from Capital One",
	"QuicksilverOne from Capital One",
	"Savor Rewards from Capital One",
	"SavorOne Rewards from Capital One",
	"Spark 2% Cash Plus",
	"Spark 1.5% Cash Select",
	"Spark 2X Miles",
	"Spark 1.5X Miles Select",
	"Venture X",
	"Cash Magnet® Card",
	"Chase Freedom Flex℠ Credit Card",
	"Chase Freedom Rise℠ Credit Card",
	"Chase Freedom Unlimited® Credit Card",
	"Ink Business Cash® Credit Card",
	"Chase Sapphire Preferred® Credit Card",
	"Chase Sapphire Reserve® Credit Card",
	"Citi Custom Cash® Card",
	"Citi Double Cash® Credit Card",
	"Citi Premier® Card",
	"Costco Anywhere Visa® Card by Citi",
	"Costco Anywhere Visa® Business Card by Citi",
	"Delta SkyMiles® Blue American Express Card",
	"Delta SkyMiles® Gold American Express Card",
	"Delta SkyMiles® Platinum American Express Card",
	"Delta SkyMiles® Platinum Business Card",
	"Delta SkyMiles® Reserve American Express Card",
	"Discover it® Cash Back Credit Card",
	"Discover it® Miles",
	"Discover it® Secured Credit Card",
	"Discover it® Student Cash Back",
	"Fidelity® Rewards Visa Signature® Credit Card",
	"Gemini Credit Card®",
	"Hilton Honors Card",
	"Hilton Honors American Express Surpass® Card",
	"Hilton Honors American Express Aspire Card",
	"HSBC Elite Credit Card",
	"IHG One Rewards Premier Credit Card",
	"Ink Business Preferred® Credit Card",
	"Ink Business Unlimited® Credit Card",
	"Marriott Bonvoy Boundless® Credit Card",
	"SoFi Credit Card",
	"Southwest Rapid Rewards® Priority Credit Card",
	"Southwest Rapid Rewards® Premier Business Credit Card",
	"TD Double Up℠ Credit Card",
	"TD First Class℠ Visa Signature® Credit Card",
	"The Business Platinum Card® from American Express",
	"The Platinum Card®",
	"United℠ Business Card",
	"United℠ Explorer Card",
	"Venture X Business",
	"Wells Fargo Active Cash® Card",
	"World of Hyatt Credit Card",
	"Wyndham Rewards Earner® Plus Card",
	"X1 Card"
] as const

export default creditCardNames
